---
- block:
  - name: Download get-pip.py
    get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp
  - name: Install pip
    command: 'python /tmp/get-pip.py'
  - name: Remove get-pip.py
    file: state=absent path=/tmp/get-pip.py