---
- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: latest

- name: Add Docker CE repository key
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker CE repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present

- name: Install docker CE
  apt:
    name: '{{ packages }}'
    state: present
    update_cache: yes
  vars:
    packages:
      - 'docker-ce=5:18.09.2~3-0~ubuntu-{{ ansible_distribution_release }}'
      - 'docker-ce-cli=5:18.09.2~3-0~ubuntu-{{ ansible_distribution_release }}'
      - containerd.io

- name: Add users to the docker group
  user:
    name: '{{ ansible_ssh_user }}'
    groups: docker
    append: yes

- name: Copy daemon.json to /etc/docker
  template:
    src: daemon.json
    dest: '/etc/docker/daemon.json'
    owner: 'root'
    group: 'root'